name: Deploy to Server

on:
  push:
    branches:
      - master

env:
  DEPLOY_PATH: "/home/u199591996/domains/tytov-roman.com"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload project to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 65002
          source: "."  # upload everything
          target: "${{ env.DEPLOY_PATH }}"